name: Hometown Value Guide
favicon: null
layout_spectrum: 0.14096605987288058
typography_spectrum: 0.6490811978001148
title: Mobile and Mailed Rewards and Savings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#942825'
    - '#92ac87'
    - '#01aef0'
    - '#272c2f'
  brandStrength: 0.3125
  lightness: 0.007002051221206784
  saturation: 0.8271565691102296
  rhythmicContrast: 0.805105245904997
purpose: []
